"""End-to-end demo: drop a real-ish LaTeX file through /upload, let the
backend route it through Claude, and screenshot the rendered AM view.

Output:
  screenshots/tex-demo.png
  screenshots/tex-demo.md   (the converted markdown)
"""
from __future__ import annotations

import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCREENSHOT_DIR = ROOT / "screenshots"
SCREENSHOT_DIR.mkdir(exist_ok=True)
PORT = 8233
SLUG = "tex-demo"

SAMPLE_TEX = r"""
\documentclass{article}
\usepackage{amsmath, amsthm, amssymb}
\usepackage{graphicx}

\newtheorem{theorem}{Theorem}
\newtheorem{definition}{Definition}

\title{The Galois Correspondence}
\author{Test Author}
\date{2026}

\begin{document}
\maketitle

\section{Introduction}

% This section sets up the basic objects.
Let $K/F$ be a finite Galois extension with Galois group $G = \mathrm{Gal}(K/F)$.
The Galois correspondence is one of the most striking results in modern algebra:
it establishes a lattice anti-isomorphism between subgroups of $G$ and
intermediate fields of the extension.

\subsection{Notation}

Throughout this note we write:
\begin{itemize}
  \item $K^H$ for the fixed field of a subgroup $H \leq G$,
  \item $\mathrm{Gal}(K/E)$ for the subgroup fixing an intermediate field $E$,
  \item $[K:E]$ for the degree of $K$ over $E$.
\end{itemize}

\section{The Correspondence}

\begin{definition}
A finite extension $K/F$ is \emph{Galois} if it is normal and separable;
equivalently, if $|\mathrm{Gal}(K/F)| = [K:F]$.
\end{definition}

\begin{theorem}[Fundamental Theorem of Galois Theory]
Let $K/F$ be a finite Galois extension with $G = \mathrm{Gal}(K/F)$.
The maps
\[
  H \;\longmapsto\; K^H, \qquad E \;\longmapsto\; \mathrm{Gal}(K/E)
\]
are mutually inverse, inclusion-reversing bijections between
\begin{enumerate}
  \item subgroups $H \leq G$, and
  \item intermediate fields $F \subseteq E \subseteq K$.
\end{enumerate}
Moreover, $[K^H : F] = [G : H]$, and the extension $K^H / F$ is Galois
if and only if $H$ is normal in $G$, in which case
$\mathrm{Gal}(K^H / F) \cong G/H$.
\end{theorem}

\subsection{An example}

\textbf{Splitting field of $x^4 - 2$.} The polynomial $x^4 - 2$ over
$\mathbb{Q}$ has splitting field $K = \mathbb{Q}(\sqrt[4]{2}, i)$.
The Galois group is the dihedral group $D_4$ of order $8$, generated by
\[
  \sigma : \sqrt[4]{2} \mapsto i\sqrt[4]{2},\; i \mapsto i,
  \qquad
  \tau : \sqrt[4]{2} \mapsto \sqrt[4]{2},\; i \mapsto -i.
\]

\section{Closing}

The lattice of subgroups of $D_4$ — and hence the lattice of intermediate
fields of $K/\mathbb{Q}$ — has the structure of two squares glued along
their corners. This is small enough to draw by hand and large enough to
be interesting.

\end{document}
"""


def wait_for_backend(port: int, timeout: float = 20.0) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=0.5):
                return True
        except OSError:
            time.sleep(0.3)
    return False


def main() -> int:
    # Use the default backend (Claude with agent fallback) — same path the
    # real user sees on a .tex drop.
    proc = subprocess.Popen(
        [sys.executable, str(ROOT / "backend.py"), str(PORT)],
        cwd=str(ROOT),
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )
    if not wait_for_backend(PORT):
        print("backend never came up")
        proc.kill()
        return 1

    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch()
            ctx = browser.new_context(viewport={"width": 1280, "height": 1400})
            page = ctx.new_page()
            page.goto(f"http://127.0.0.1:{PORT}/")
            page.wait_for_function(
                "() => document.getElementById('doc-select')?.value",
                timeout=10000,
            )

            print("[demo] sending .tex through /upload …")
            t0 = time.time()
            upload = page.evaluate(
                """async (texSource) => {
                    const blob = new Blob([texSource], { type: 'text/x-tex' });
                    const form = new FormData();
                    form.append('file', blob, 'galois.tex');
                    const r = await fetch('/upload', { method: 'POST', body: form });
                    return { status: r.status, body: await r.json() };
                }""",
                SAMPLE_TEX,
            )
            print(f"[demo] /upload returned in {time.time()-t0:.1f}s: "
                  f"status={upload.get('status')} body={upload.get('body')}")

            if upload.get("status") != 200:
                print("[demo] upload failed; aborting")
                return 1
            slug = upload.get("body", {}).get("slug")
            converter = upload.get("body", {}).get("converter")
            if not upload.get("body", {}).get("converted"):
                print("[demo] backend did not run server-side conversion "
                      "(probably no ANTHROPIC_API_KEY). Aborting visual check.")
                return 2
            print(f"[demo] converted via: {converter}")

            page.wait_for_function(
                f"() => document.getElementById('doc-select')?.value === '{slug}'",
                timeout=15000,
            )
            page.wait_for_timeout(1500)

            shot = SCREENSHOT_DIR / "tex-demo.png"
            page.screenshot(path=str(shot), full_page=True)
            converted = (ROOT / "docs" / slug / "current.md").read_text(
                encoding="utf-8"
            )
            (SCREENSHOT_DIR / "tex-demo.md").write_text(converted, encoding="utf-8")
            print(f"[demo] screenshot -> {shot}")
            print(f"[demo] markdown    -> {SCREENSHOT_DIR / 'tex-demo.md'}")
            browser.close()
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
        shutil.rmtree(ROOT / "docs" / SLUG, ignore_errors=True)

    return 0


if __name__ == "__main__":
    sys.exit(main())
